# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2023-02-18 09:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ButtonClick',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stupid_count', models.IntegerField(default=0)),
                ('fat_count', models.IntegerField(default=0)),
                ('dumb_count', models.IntegerField(default=0)),
            ],
        ),
    ]
