# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2023-02-18 11:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buttonclick',
            old_name='dumb_count',
            new_name='Dumb',
        ),
        migrations.RenameField(
            model_name='buttonclick',
            old_name='fat_count',
            new_name='Fat',
        ),
        migrations.RenameField(
            model_name='buttonclick',
            old_name='stupid_count',
            new_name='Stupid',
        ),
    ]
